import assert from "node:assert/strict";
import fs from "node:fs";
import { after, before, test } from "node:test";
import { PGlite } from "@electric-sql/pglite";

const db = new PGlite();
const owner = "11111111-1111-4111-8111-111111111111"; const other = "22222222-2222-4222-8222-222222222222"; const script = "33333333-3333-4333-8333-333333333333"; const scene = "44444444-4444-4444-8444-444444444444"; const hash = "a".repeat(64);
before(async () => { await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$; grant usage on schema public,auth to anon,authenticated,service_role; create table public.writer_scripts(id uuid primary key,owner_id uuid not null references auth.users(id) on delete cascade,title text not null,document jsonb not null,schema_version integer not null default 1,revision bigint not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now()); create table public.plan_entitlements(plan_code text not null,entitlement_key text not null,access_value boolean,allowance_value numeric,allowance_unit text,unlimited boolean not null default false,fair_use boolean not null default false,primary key(plan_code,entitlement_key)); alter table public.writer_scripts enable row level security; grant select on public.writer_scripts to authenticated; create policy owner_read on public.writer_scripts for select to authenticated using(owner_id=auth.uid()); insert into auth.users values('${owner}'),('${other}'); insert into writer_scripts values('${script}','${owner}','QA','{"type":"doc","content":[]}',1,1,now(),now());`); await db.exec(fs.readFileSync("supabase/migrations/20260930220000_writer_narrative_pulse_v1.sql", "utf8")); await db.exec(fs.readFileSync("supabase/migrations/20260930230000_writer_service_role_script_read.sql", "utf8")); });
after(() => db.close());
async function as(role: "postgres" | "service_role" | "authenticated", uid="") { await db.exec("reset role"); await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role',$2,false)",[uid,role]); if(role!=="postgres") await db.exec(`set role ${role}`); }
test("service reservation creates analysis and ledger rows", async () => { await as("service_role"); const result=await db.query("select writer_reserve_narrative_pulse($1,$2,$3,$4,'narrative-pulse-v1','gpt-5.6-terra',$5,50000,10000000) value",[owner,"55555555-5555-4555-8555-555555555551",script,hash,"b".repeat(64)]); assert.equal((result.rows[0] as {value:{status:string}}).value.status,"reserved"); await as("postgres"); assert.equal(((await db.query("select count(*)::int count from writer_narrative_pulse_operations")).rows[0] as {count:number}).count,1); });
test("settlement records usage, cost and fresh status", async () => { await as("service_role"); await db.query("select writer_settle_narrative_pulse($1,$2,'completed',null,1200,200,400,0,7800,1900)",[owner,"55555555-5555-4555-8555-555555555551"]); await as("postgres"); assert.deepEqual((await db.query("select status,actual_cost_microusd,latency_ms from writer_narrative_pulse_operations")).rows[0],{status:"completed",actual_cost_microusd:7800,latency_ms:1900}); assert.equal(((await db.query("select status from writer_narrative_pulse_analyses")).rows[0] as {status:string}).status,"fresh"); });
test("milestones support manual authority and deleted-scene review status", async () => { await as("postgres"); await db.query("insert into writer_narrative_pulse_milestones(owner_id,script_id,scene_id,milestone_type,label,status,source,fingerprint) values($1,$2,$3,'custom','Hito humano','manual','user','user:1')",[owner,script,scene]); const row=(await db.query("select status,source,moved_by_user from writer_narrative_pulse_milestones")).rows[0]; assert.deepEqual(row,{status:"manual",source:"user",moved_by_user:false}); });
test("owner RLS exposes analysis data but never operations or writes", async () => { await as("authenticated",owner); assert.equal(((await db.query("select count(*)::int count from writer_narrative_pulse_analyses")).rows[0] as {count:number}).count,1); assert.equal(((await db.query("select count(*)::int count from writer_narrative_pulse_milestones")).rows[0] as {count:number}).count,1); await assert.rejects(db.query("select * from writer_narrative_pulse_operations"),/permission denied/u); await assert.rejects(db.query("delete from writer_narrative_pulse_milestones"),/permission denied/u); });
test("another owner sees no Pulse state", async () => { await as("authenticated",other); assert.equal(((await db.query("select count(*)::int count from writer_narrative_pulse_analyses")).rows[0] as {count:number}).count,0); assert.equal(((await db.query("select count(*)::int count from writer_narrative_pulse_milestones")).rows[0] as {count:number}).count,0); });
test("entitlement is available without a commercial gate", async () => { await as("postgres"); assert.deepEqual((await db.query("select plan_code,entitlement_key,access_value from plan_entitlements where entitlement_key='writer.narrative_pulse'")).rows[0],{plan_code:"free",entitlement_key:"writer.narrative_pulse",access_value:true}); });
test("service role can read scripts but receives no script write privileges", async () => { await as("service_role"); assert.equal(((await db.query("select count(*)::int count from writer_scripts where id=$1", [script])).rows[0] as {count:number}).count, 1); await assert.rejects(db.query("insert into writer_scripts(id,owner_id,title,document) values(gen_random_uuid(),$1,'No', '{}'::jsonb)", [owner]), /permission denied/u); await assert.rejects(db.query("update writer_scripts set title='No' where id=$1", [script]), /permission denied/u); await assert.rejects(db.query("delete from writer_scripts where id=$1", [script]), /permission denied/u); });
