export const developedIdea = `Lucía trabaja clasificando paquetes en una ciudad donde cada objeto lleva una etiqueta con el nombre de su dueño. Su hija desapareció después de que la empresa de mensajería corrigiera una etiqueta. Lucía quiere recuperar el registro original antes del amanecer, cuando se destruyen los archivos. El jefe de seguridad, que sabe que la empresa borra personas del registro civil, le cierra el paso. Si falla, su hija perderá también los recuerdos de quienes la conocieron. Todo empieza cuando Lucía recibe un paquete con su propia letra, fechado mañana. Ve una escena en el depósito de etiquetas mojadas, otra en un tren vacío y una discusión sin palabras ante la puerta de su casa. Al final encuentra a su hija, pero debe entregar su propio nombre para que vuelva a ser reconocida. Quiero una historia íntima, tensa y triste sobre la memoria y el cuidado.`;

export const minimalIdea = "Un hombre despierta cada día recordando la vida de otra persona.";

export const longIdea = `La ciudad costera de Puerto Sal guarda la hora en una torre que nadie ha visto funcionar. Cada mañana las campanas suenan a las seis, aunque hace veinte años quitaron las campanas. Me interesa que esto no se explique enseguida. Mara, una reparadora de radios, oye una voz entre las interferencias y reconoce la respiración de su padre. Ella cree que murió durante una tormenta, pero en mi primera nota escribí que él vive en el faro y que sólo finge estar muerto. Ambas cosas están en mis apuntes y todavía no he decidido cuál es verdad. Mara no es detective; arregla objetos porque le incomoda hablar con personas.

Quiero una apertura en el taller, con una radio que enciende sola mientras Mara cuenta tornillos. Nada debe saltar ni asustar de modo fácil. La voz le dice una fecha del futuro y menciona el nombre de un barco que dejó de existir. Mara busca a Tomás, un viejo operador de puerto, porque él conoce las frecuencias antiguas. Tomás le enseña una libreta de mareas con varias páginas arrancadas. En la página que queda hay una marca roja a la misma hora en que suena la torre. Es una pista visual, pero no quiero que los personajes expliquen todo mirando el cuaderno.

En otra versión, Mara tiene una hermana llamada Inés que abandonó el pueblo. Inés regresa para vender la casa familiar y no cree en las voces. Lo importante entre ellas es una herida cotidiana: Mara cuidó a su madre durante años y siente que Inés apareció sólo cuando había algo que vender. Inés, en cambio, recuerda que Mara le pidió irse porque discutían sin descanso. Ninguna tiene toda la razón. Me gustaría que la relación pueda sostener la película aunque el misterio de la torre resulte más pequeño de lo que parece. Inés podría ayudar a descifrar una señal por sus conocimientos de cartografía.

La amenaza externa quizá sea la próxima marea grande. Los mapas oficiales dicen que el dique es seguro. Tomás guarda fotografías que muestran grietas debajo del agua. Si la ciudad espera al aviso del gobierno, tal vez no quede tiempo para evacuar. Sin embargo, no quiero convertir la historia en un thriller de desastre convencional. La marea debe presionar a las personas para decidir a quién creen y qué están dispuestas a perder. El alcalde no sería un villano plano. Tiene miedo de provocar un éxodo que destruya la economía local si anuncia un riesgo que no puede demostrar.

Imagino una escena de noche en la playa: cientos de peces depositados en líneas demasiado rectas. Mara e Inés los encuentran mientras buscan el acceso al cable submarino que alimentaba la torre. La imagen puede ser hermosa y equivocada a la vez. Una niña del pueblo les pregunta si los peces estaban intentando escribir algo. No hace falta que la niña se convierta en personaje central; su pregunta basta. Otra imagen es un grupo de vecinos escuchando radios apagadas en sus cocinas. Cada radio reproduce una voz distinta, o quizá todos oyen la misma voz y la interpretan de manera diferente.

El giro que estoy probando es que la señal no viene del pasado ni del futuro, sino de decisiones que no se tomaron. Cuando alguien del puerto elige una ruta, otra posibilidad queda resonando en el cable. No sé si esta regla debe ser literal o una forma de hablar del duelo. Si es literal, necesito límites claros: nadie puede consultar cualquier destino ni recuperar a quien perdió. La señal quizá sólo aparece cuando una decisión colectiva está cerca y no ofrece instrucciones completas. Si se vuelve demasiado poderosa, la historia pierde el dolor de elegir sin garantías.

Hay un punto medio donde Mara sube al faro y encuentra un abrigo de su padre todavía húmedo. Eso parece confirmar que vive, pero también podría haber otra explicación. En una versión él murió años antes y el abrigo llegó arrastrado por el agua. En otra, él se escondió porque sabía que la torre alteraba los recuerdos. Quiero que la película reconozca esas contradicciones como dudas mías, no como pistas calculadas. El asistente debería preguntarme cuál versión quiero sostener antes de proponer una respuesta cerrada. Tal vez la pregunta verdadera sea qué necesita Mara de su padre ahora.

El final no está decidido. Veo a las hermanas en el dique al amanecer. Una podría quedarse para mantener abierto un paso mientras la otra guía a la gente hacia terreno alto. No quiero que una muera sólo para darle dramatismo a la otra. También veo a Mara apagando por fin la torre y aceptando que algunas voces dejarán de escucharse. Sería una elección irreversible, pero necesito saber antes qué gana y qué pierde la ciudad. Me importa que el final tenga una consecuencia compartida, no una solución secreta que sólo Mara comprenda. La última imagen quizá sea una radio silenciosa junto a una ventana abierta.

El tono debe ser sobrio y cercano a los personajes. Hay misterio, pero no quiero una explicación científica extensa ni una criatura escondida bajo el muelle. La película trata de las versiones incompatibles que una familia conserva de lo mismo. El sonido del viento, los espacios vacíos y los objetos reparados pueden llevar ese tema. No sé todavía cuál es el objetivo concreto de Mara durante el primer acto: encontrar al padre, reparar la torre o impedir que el dique falle. Esa pregunta debería quedar abierta en el análisis, igual que la verdad del padre y la naturaleza de la señal.`;
