import fs from 'node:fs';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
import {execFileSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import path from 'node:path';

export const TEST_REF='ezlycwkuzkwcnhrhiruv';
export function testSql(sql){
  assert.equal(process.env.FILMATTA_RUN_REMOTE_TESTS,TEST_REF);
  const file=path.join(tmpdir(),`filmatta-test-query-${randomUUID()}.sql`);
  try{
    fs.writeFileSync(file,sql);
    const command=`& npx supabase db query --linked --project-ref ${TEST_REF} --file '${file.replaceAll("'","''")}' --output json; exit $LASTEXITCODE`;
    const output=execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
    return JSON.parse(output).rows;
  }finally{fs.rmSync(file,{force:true});}
}
export function testConfiguration(){
  assert.equal(process.env.FILMATTA_RUN_REMOTE_TESTS,TEST_REF,'Explicit Test opt-in required.');
  assert.ok(process.env.FILMATTA_TEST_ENV_FILE,'Supply the existing Test-only env file path.');
  const allowed=new Set(['NEXT_PUBLIC_SUPABASE_URL','NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY','SUPABASE_SERVICE_ROLE_KEY','BILLING_TEST_SUPABASE_PROJECT_REF']);
  const config={};
  for(const line of fs.readFileSync(process.env.FILMATTA_TEST_ENV_FILE,'utf8').split(/\r?\n/)){
    const match=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if(match&&allowed.has(match[1])) config[match[1]]=match[2].replace(/^(['"])(.*)\1$/,'$2');
  }
  assert.equal(config.NEXT_PUBLIC_SUPABASE_URL,`https://${TEST_REF}.supabase.co`);
  assert.equal(config.BILLING_TEST_SUPABASE_PROJECT_REF,TEST_REF);
  assert.ok(config.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
  const service=config.SUPABASE_SERVICE_ROLE_KEY;
  assert.ok(service);
  if(service.startsWith('eyJ')) assert.equal(JSON.parse(Buffer.from(service.split('.')[1],'base64url')).ref,TEST_REF,'Refuse mismatched service key.');
  return config;
}
export async function withTestUsers(run){
  const config=testConfiguration();
  const client=(key)=>createClient(config.NEXT_PUBLIC_SUPABASE_URL,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  const adminSetup=client(config.SUPABASE_SERVICE_ROLE_KEY);
  const anon=client(config.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
  const users=[];
  const prefix=`catalog-${randomUUID()}`;
  try{
    for(const kind of ['owner','stranger','admin']){
      const email=`${prefix}-${kind}@example.invalid`;
      const password=randomBytes(24).toString('base64url')+'aA1!';
      const fullName=`Integration ${kind} PrivateSurname`;
      const result=await adminSetup.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:fullName}});
      assert.equal(result.error,null,'Test user creation failed.');
      const user={id:result.data.user.id,email,fullName,kind};users.push(user);
      const normal=client(config.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
      const signed=await normal.auth.signInWithPassword({email,password});
      assert.equal(signed.error,null,'Real Auth sign-in failed.');
      user.client=normal;
      if(kind==='admin'){
        const promoted=testSql(`update public.profiles set role='admin' where id='${user.id}' and exists(select 1 from auth.users where id='${user.id}' and email='${email}') returning id;`);
        assert.equal(promoted.length,1);
      }
    }
    await run({prefix,anon,owner:users[0],stranger:users[1],admin:users[2]});
  }finally{
    for(const user of users){
      // Only users generated by this run can enter the cleanup list.
      assert.ok(user.email.startsWith(prefix+'-'));
      const result=await adminSetup.auth.admin.deleteUser(user.id);
      assert.equal(result.error,null,'Temporary Test user cleanup failed.');
    }
  }
}

export function checked(result){assert.equal(result.error,null);return result.data;}
