import type { ContextualTip } from "./types";

export const CONTEXTUAL_TIPS: readonly ContextualTip[] = [
  {
    id: "learn-no-progress-start",
    vertical: "learn",
    states: ["noProgress"],
    text: "Empieza por la primera lección. Tu progreso se irá guardando conforme avances.",
    mattiPose: "focused",
  },
  {
    id: "learn-no-progress-syllabus",
    vertical: "learn",
    states: ["noProgress"],
    text: "Revisa el temario antes de empezar. Así sabrás qué vas a construir durante el curso.",
    mattiPose: "neutral",
  },
  {
    id: "learn-started-resume",
    vertical: "learn",
    states: ["started"],
    text: "Continúa desde donde lo dejaste. No necesitas volver a empezar el módulo.",
    mattiPose: "focused",
  },
  {
    id: "learn-started-finish",
    vertical: "learn",
    states: ["started"],
    text: "Una lección terminada vale más que cinco abiertas a medias.",
    mattiPose: "neutral",
  },
  {
    id: "learn-halfway-review",
    vertical: "learn",
    states: ["halfway"],
    text: "Ya cruzaste la mitad. Revisa lo anterior sólo si algo de la siguiente lección no queda claro.",
    mattiPose: "agree",
  },
  {
    id: "learn-halfway-practice",
    vertical: "learn",
    states: ["halfway"],
    text: "Prueba aplicar una idea del curso antes de seguir. La práctica fija mejor lo aprendido.",
    mattiPose: "focused",
  },
  {
    id: "learn-almost-finish",
    vertical: "learn",
    states: ["almostCompleted"],
    text: "Ya estás cerca del final. Termina las pendientes antes de volver a las anteriores.",
    mattiPose: "happy",
  },
  {
    id: "learn-almost-close",
    vertical: "learn",
    states: ["almostCompleted"],
    text: "Quedan pocas lecciones. Cierra el recorrido y después vuelve a tus favoritas.",
    mattiPose: "focused",
  },
  {
    id: "learn-completed-apply",
    vertical: "learn",
    states: ["completed"],
    text: "Curso terminado. Ahora lo útil es llevar al menos una idea a un proyecto real.",
    mattiPose: "happy",
  },
  {
    id: "learn-completed-return",
    vertical: "learn",
    states: ["completed"],
    text: "Puedes volver a cualquier lección cuando necesites refrescar algo.",
    mattiPose: "agree",
  },
  {
    id: "learn-preview-completed",
    vertical: "learn",
    states: ["previewCompleted"],
    text: "Ya terminaste las lecciones gratuitas. El resto del curso continúa con FILMATTA Plus.",
    mattiPose: "thinking",
  },
  {
    id: "learn-premium-locked-video",
    vertical: "learn",
    states: ["premiumLocked"],
    text: "Puedes revisar el contenido de esta lección. La reproducción del video forma parte de Plus.",
    mattiPose: "neutral",
  },
  {
    id: "learn-premium-locked-syllabus",
    vertical: "learn",
    states: ["premiumLocked"],
    text: "Antes de decidir, revisa el temario completo y mira qué otras lecciones incluye el curso.",
    mattiPose: "thinking",
  },
  {
    id: "learn-default-camera",
    vertical: "learn",
    states: ["default"],
    text: "Si algo parece obvio, pruébalo en cámara. Ahí suelen aparecer las preguntas buenas.",
    mattiPose: "focused",
  },
  {
    id: "learn-default-decisions",
    vertical: "learn",
    states: ["default"],
    text: "Anota decisiones, no sólo conceptos. Es más fácil llevarlas al siguiente rodaje.",
    mattiPose: "neutral",
  },
  {
    id: "learn-returned",
    vertical: "learn",
    states: ["returned"],
    text: "Bienvenido de vuelta. Continúa desde tu última lección activa.",
    mattiPose: "neutral",
  },
  {
    id: "learn-inactive",
    vertical: "learn",
    states: ["inactive"],
    text: "Hace tiempo que no visitas este curso. Retomar una sola lección es suficiente para volver al ritmo.",
    mattiPose: "thinking",
  },
  {
    id: "learn-default-context",
    vertical: "learn",
    states: ["default"],
    text: "¿Algo no quedó claro? Revisa la descripción y el contexto de la siguiente lección antes de repetir.",
    mattiPose: "curious",
  },
  {
    id: "learn-default-material",
    vertical: "learn",
    states: ["default"],
    text: "Cuando un concepto afecte exposición, audio o foco, compáralo directamente con material real.",
    mattiPose: "focused",
  },
  {
    id: "learn-default-progress",
    vertical: "learn",
    states: ["default"],
    text: "Tu progreso refleja lecciones completadas, no cuánto tiempo dejaste abierto el reproductor.",
    mattiPose: "agree",
  },
  {
    id: "profile-empty",
    vertical: "profile",
    states: ["emptyProfile"],
    text: "Empieza por lo esencial: disciplina, ciudad y una descripción breve de lo que haces.",
    mattiPose: "focused",
  },
  {
    id: "profile-photo",
    vertical: "profile",
    states: ["missingPhoto"],
    text: "Una foto clara ayuda a que tu perfil se sienta humano antes de mostrar tu trabajo.",
    mattiPose: "neutral",
  },
  {
    id: "profile-bio",
    vertical: "profile",
    states: ["missingBio"],
    text: "Tu bio no necesita contar toda tu historia. Explica qué haces y qué tipo de proyectos buscas.",
    mattiPose: "thinking",
  },
  {
    id: "profile-discipline",
    vertical: "profile",
    states: ["missingDiscipline"],
    text: "Selecciona tus disciplinas principales. FILMATTA podrá contextualizar mejor tu perfil.",
    mattiPose: "focused",
  },
  {
    id: "profile-reel-short",
    vertical: "profile",
    states: ["missingReel"],
    text: "Un reel corto suele decir más que una lista larga de habilidades.",
    mattiPose: "thinking",
  },
  {
    id: "profile-reel-start",
    vertical: "profile",
    states: ["missingReel"],
    text: "Empieza con tu mejor trabajo. No necesitas esperar a tener veinte proyectos.",
    mattiPose: "focused",
  },
  {
    id: "profile-availability",
    vertical: "profile",
    states: ["missingAvailability"],
    text: "Indicar disponibilidad evita contactos que no puedes atender.",
    mattiPose: "neutral",
  },
  {
    id: "profile-half",
    vertical: "profile",
    states: ["profile50"],
    text: "Tu perfil ya tiene una base. El siguiente salto suele estar en mostrar trabajo real.",
    mattiPose: "focused",
  },
  {
    id: "profile-seventy",
    vertical: "profile",
    states: ["profile70"],
    text: "Tu perfil está bastante completo. Revisa reel, créditos y disponibilidad.",
    mattiPose: "agree",
  },
  {
    id: "profile-complete",
    vertical: "profile",
    states: ["profileComplete"],
    text: "Perfil completo. Ahora mantenlo actualizado cuando termines un proyecto.",
    mattiPose: "happy",
  },
  {
    id: "profile-default-first",
    vertical: "profile",
    states: ["default"],
    text: "Pon primero el trabajo por el que quieres que te contraten.",
    mattiPose: "neutral",
  },
  {
    id: "profile-default-quality",
    vertical: "profile",
    states: ["default"],
    text: "Más piezas no siempre significan mejor portfolio. Prioriza las que expliquen tu nivel actual.",
    mattiPose: "thinking",
  },
  {
    id: "profile-default-credits",
    vertical: "profile",
    states: ["default"],
    text: "Describe responsabilidades concretas en tus créditos.",
    mattiPose: "focused",
  },
  {
    id: "profile-default-disciplines",
    vertical: "profile",
    states: ["default"],
    text: "Si trabajas en varias disciplinas, ordénalas por relevancia y no por cantidad.",
    mattiPose: "neutral",
  },
  {
    id: "profile-default-review",
    vertical: "profile",
    states: ["default"],
    text: "Revisa tu perfil como si fueras alguien que necesita contratarte en cinco minutos.",
    mattiPose: "curious",
  },
  {
    id: "profile-default-location",
    vertical: "profile",
    states: ["default"],
    text: "Ciudad y disponibilidad son datos pequeños que pueden decidir un contacto.",
    mattiPose: "focused",
  },
  {
    id: "profile-default-clear",
    vertical: "profile",
    states: ["default"],
    text: "No hace falta sonar corporativo. Hace falta ser claro.",
    mattiPose: "agree",
  },
  {
    id: "profile-default-reedit",
    vertical: "profile",
    states: ["default"],
    text: "Si tu reel necesita demasiada explicación, quizá conviene editarlo otra vez.",
    mattiPose: "thinking",
  },
  {
    id: "profile-default-update",
    vertical: "profile",
    states: ["default"],
    text: "Actualiza créditos después del proyecto, no seis meses después.",
    mattiPose: "neutral",
  },
  {
    id: "profile-default-answer",
    vertical: "profile",
    states: ["default"],
    text: "Tu perfil debería responder rápido: qué haces, dónde estás y qué tan bien lo haces.",
    mattiPose: "focused",
  },
  {
    id: "project-new",
    vertical: "project",
    states: ["newProject"],
    text: "Empieza definiendo qué vas a producir, cuándo y qué necesitas para hacerlo.",
    mattiPose: "focused",
  },
  {
    id: "project-dates",
    vertical: "project",
    states: ["missingDates"],
    text: "Sin fechas es difícil saber quién puede participar. Aunque sean tentativas, agrégalas.",
    mattiPose: "thinking",
  },
  {
    id: "project-crew",
    vertical: "project",
    states: ["missingCrew"],
    text: "Define primero los roles imprescindibles. El equipo puede crecer después.",
    mattiPose: "focused",
  },
  {
    id: "project-budget",
    vertical: "project",
    states: ["missingBudget"],
    text: "Aclara si el proyecto es pagado, colaboración o estudiantil antes de buscar equipo.",
    mattiPose: "neutral",
  },
  {
    id: "project-location",
    vertical: "project",
    states: ["missingLocation"],
    text: "Una locación cambia logística, sonido, luz y horarios. No la dejes para el final.",
    mattiPose: "thinking",
  },
  {
    id: "project-call-sheet",
    vertical: "project",
    states: ["missingCallSheet"],
    text: "Cuando el rodaje esté cerca, concentra horarios, contactos y dirección en un call sheet.",
    mattiPose: "focused",
  },
  {
    id: "project-active-info",
    vertical: "project",
    states: ["activeProject"],
    text: "Un proyecto activo necesita información actualizada más que una descripción perfecta.",
    mattiPose: "neutral",
  },
  {
    id: "project-active-date",
    vertical: "project",
    states: ["activeProject"],
    text: "Si cambió una fecha importante, actualízala antes de seguir reclutando.",
    mattiPose: "focused",
  },
  {
    id: "project-finished",
    vertical: "project",
    states: ["finishedProject"],
    text: "Proyecto terminado. Añade créditos y resultados mientras todos los datos siguen frescos.",
    mattiPose: "happy",
  },
  {
    id: "project-default-vacancy",
    vertical: "project",
    states: ["default"],
    text: "Antes de publicar una vacante, piensa qué necesita saber alguien para decir sí o no.",
    mattiPose: "thinking",
  },
  {
    id: "project-default-brief",
    vertical: "project",
    states: ["default"],
    text: "Un buen brief ahorra mensajes después.",
    mattiPose: "focused",
  },
  {
    id: "project-default-deliverables",
    vertical: "project",
    states: ["default"],
    text: "Especifica entregables cuando contrates edición, sonido, VFX o diseño.",
    mattiPose: "neutral",
  },
  {
    id: "project-default-decisions",
    vertical: "project",
    states: ["default"],
    text: "Define quién toma decisiones finales antes de empezar producción.",
    mattiPose: "focused",
  },
  {
    id: "project-default-clarity",
    vertical: "project",
    states: ["default"],
    text: "Si todos entienden algo distinto del proyecto, todavía falta claridad en el brief.",
    mattiPose: "curious",
  },
  {
    id: "project-default-essential",
    vertical: "project",
    states: ["default"],
    text: "Separa lo indispensable de lo deseable en crew y equipo.",
    mattiPose: "neutral",
  },
  {
    id: "project-default-budget",
    vertical: "project",
    states: ["default"],
    text: "Un presupuesto incompleto sigue siendo mejor que ningún rango de presupuesto.",
    mattiPose: "thinking",
  },
  {
    id: "project-default-revisions",
    vertical: "project",
    states: ["default"],
    text: "Las revisiones también cuestan tiempo. Define límites antes de postproducción.",
    mattiPose: "focused",
  },
  {
    id: "project-default-credits",
    vertical: "project",
    states: ["default"],
    text: "Los créditos correctos también son parte de cerrar bien un proyecto.",
    mattiPose: "agree",
  },
  {
    id: "project-default-decisions-log",
    vertical: "project",
    states: ["default"],
    text: "Guarda decisiones importantes dentro del proyecto, no sólo en chats dispersos.",
    mattiPose: "focused",
  },
  {
    id: "project-default-production",
    vertical: "project",
    states: ["default"],
    text: "Las ideas necesitan equipo, fechas y responsables para convertirse en producción.",
    mattiPose: "neutral",
  },
  {
    id: "location-browsing-logistics",
    vertical: "location",
    states: ["browsing"],
    text: "Una locación bonita no siempre funciona para rodaje. Revisa ruido, energía y acceso.",
    mattiPose: "focused",
  },
  {
    id: "location-browsing-scene",
    vertical: "location",
    states: ["browsing"],
    text: "Mira primero las necesidades de tu escena y después la estética.",
    mattiPose: "neutral",
  },
  {
    id: "location-noise",
    vertical: "location",
    states: ["missingNoiseInfo"],
    text: "Pregunta por ruido exterior, vecinos, tráfico y horarios antes de grabar diálogo.",
    mattiPose: "thinking",
  },
  {
    id: "location-power",
    vertical: "location",
    states: ["missingPowerInfo"],
    text: "Confirma contactos eléctricos y carga disponible si vas a llevar iluminación.",
    mattiPose: "focused",
  },
  {
    id: "location-parking",
    vertical: "location",
    states: ["missingParking"],
    text: "Estacionamiento y descarga de equipo pueden cambiar por completo la logística.",
    mattiPose: "neutral",
  },
  {
    id: "location-permissions",
    vertical: "location",
    states: ["missingPermissions"],
    text: "Confirma permisos por escrito cuando el espacio no sea tuyo.",
    mattiPose: "thinking",
  },
  {
    id: "location-saved",
    vertical: "location",
    states: ["savedLocations"],
    text: "Guarda varias opciones antes de decidir. Compararlas juntas hace más claras las diferencias.",
    mattiPose: "agree",
  },
  {
    id: "location-project-empty",
    vertical: "location",
    states: ["projectHasNoLocation"],
    text: "Empieza por los requisitos de la escena: tamaño, luz, sonido, acceso y horario.",
    mattiPose: "focused",
  },
  {
    id: "location-default-areas",
    vertical: "location",
    states: ["default"],
    text: "Pregunta qué áreas están incluidas realmente en la renta.",
    mattiPose: "neutral",
  },
  {
    id: "location-default-move",
    vertical: "location",
    states: ["default"],
    text: "Revisa si puedes mover muebles, decorar o fijar equipo.",
    mattiPose: "focused",
  },
  {
    id: "location-default-window",
    vertical: "location",
    states: ["default"],
    text: "Una ventana hermosa puede convertirse en un problema si no puedes controlar la luz.",
    mattiPose: "thinking",
  },
  {
    id: "location-default-facilities",
    vertical: "location",
    states: ["default"],
    text: "Confirma baños, camerino y área de espera cuando el crew sea grande.",
    mattiPose: "neutral",
  },
  {
    id: "location-default-hours",
    vertical: "location",
    states: ["default"],
    text: "Pregunta por restricciones de horario antes de planear llamados nocturnos.",
    mattiPose: "focused",
  },
  {
    id: "location-default-sound",
    vertical: "location",
    states: ["default"],
    text: "¿Puedes grabar sonido directo aquí? Esa pregunta puede ahorrar horas de post.",
    mattiPose: "curious",
  },
  {
    id: "location-default-visit",
    vertical: "location",
    states: ["default"],
    text: "Visita la locación a una hora parecida a la del rodaje si la luz natural importa.",
    mattiPose: "thinking",
  },
  {
    id: "location-default-unload",
    vertical: "location",
    states: ["default"],
    text: "Calcula dónde descargarás equipo antes de llegar con todo el crew.",
    mattiPose: "focused",
  },
  {
    id: "location-default-lens",
    vertical: "location",
    states: ["default"],
    text: "Una foto gran angular puede hacer que un espacio parezca mucho más grande.",
    mattiPose: "neutral",
  },
  {
    id: "location-default-notes",
    vertical: "location",
    states: ["default"],
    text: "Guarda notas de scouting. Después de cinco lugares empiezan a mezclarse.",
    mattiPose: "agree",
  },
  {
    id: "location-default-effects",
    vertical: "location",
    states: ["default"],
    text: "Si habrá humo, lluvia, animales o efectos, confírmalo con el propietario antes.",
    mattiPose: "focused",
  },
  {
    id: "location-default-balance",
    vertical: "location",
    states: ["default"],
    text: "Una buena locación resuelve la escena sin crear tres problemas nuevos.",
    mattiPose: "neutral",
  },
];
